import type { FormFieldDef, ProcessDef, ProcessOutcome, WorkflowTemplate } from '@/types';

/**
 * Default workflow templates (PRD §4 Subcont and §5 New Mold).
 * Admins can edit these in Settings → Workflow; projects keep a snapshot of
 * the template version they were created with.
 */

type DefInput = Partial<ProcessDef> & Pick<ProcessDef, 'key' | 'name' | 'picRole'>;

function def(input: DefInput): ProcessDef {
  return {
    shortName: input.name,
    description: '',
    kind: 'task',
    actorRoles: [input.picRole],
    uploadRoles: input.actorRoles ?? [input.picRole],
    isMandatory: true,
    requiresDocument: false,
    requiredDocTypes: [],
    suggestedDocTypes: input.requiredDocTypes ?? [],
    requiresApproval: false,
    waitingType: 'internal',
    defaultNextAction: `Selesaikan ${input.name}`,
    durationDays: 3,
    folder: 'Lainnya',
    recordType: 'general',
    fields: [],
    ...input,
  };
}

const TESTS = ['Visual', 'Dimension', 'Weight', 'Leak', 'Drop', 'Vacuum', 'Assembly', 'Function', 'Appearance', 'Color', 'Printing', 'Lainnya'];
const TRIAL_RESULT = ['OK', 'OK dengan catatan', 'NG'];
const MATERIAL_TYPES = ['PP', 'PE', 'HDPE', 'LDPE', 'PET', 'PETG', 'ABS', 'AS', 'PCR', 'Lainnya'];

const requestFields = (numberLabel: string): FormFieldDef[] => [
  { key: 'requestNumber', label: numberLabel, type: 'text', required: true, placeholder: 'mis. NPR-2026-014' },
  { key: 'customer', label: 'Customer', type: 'text', required: true, prefill: 'customer' },
  { key: 'projectName', label: 'Project Name', type: 'text', required: true, prefill: 'projectName' },
  { key: 'product', label: 'Product', type: 'text', required: true, prefill: 'productName' },
  { key: 'requestDate', label: 'Request Date', type: 'date', required: true, prefill: 'today' },
  { key: 'customerRequest', label: 'Customer Request', type: 'textarea', required: true, prefill: 'customerRequest' },
  { key: 'quantity', label: 'Quantity (pcs)', type: 'number', required: true },
  { key: 'material', label: 'Material', type: 'text', required: true },
  { key: 'color', label: 'Color', type: 'text' },
  { key: 'specification', label: 'Specification', type: 'textarea' },
  { key: 'targetDate', label: 'Target Date', type: 'date' },
  { key: 'salesPic', label: 'Sales PIC', type: 'user', role: 'admin_sales', prefill: 'salesPic', required: true },
];

const feedbackFields: FormFieldDef[] = [
  { key: 'feedback', label: 'Feedback', type: 'textarea', required: true },
  { key: 'feasibility', label: 'Feasibility', type: 'select', required: true, options: ['Feasible', 'Feasible dengan catatan', 'Not Feasible'] },
  { key: 'technicalNotes', label: 'Technical Notes', type: 'textarea' },
  { key: 'estimatedTimeline', label: 'Estimated Timeline', type: 'text', placeholder: 'mis. 6 minggu' },
  { key: 'requiredInformation', label: 'Required Information', type: 'textarea' },
  { key: 'risk', label: 'Risk', type: 'textarea' },
  { key: 'recommendation', label: 'Recommendation', type: 'textarea' },
];

const trialFields = (prefix: string): FormFieldDef[] => [
  { key: 'trialNumber', label: `${prefix} Number`, type: 'text', helper: 'Kosongkan untuk nomor otomatis' },
  { key: 'trialDate', label: `${prefix} Date`, type: 'date', required: true, prefill: 'today' },
  { key: 'machine', label: 'Machine', type: 'text', required: true },
  { key: 'mold', label: 'Mold', type: 'text' },
  { key: 'cavity', label: 'Cavity', type: 'number' },
  { key: 'material', label: 'Material', type: 'text' },
  { key: 'parameter', label: 'Parameter', type: 'textarea' },
  { key: 'quantity', label: 'Quantity (pcs)', type: 'number' },
  { key: 'tests', label: 'Test', type: 'multiselect', options: TESTS },
  { key: 'trialResult', label: `${prefix} Result`, type: 'select', required: true, options: TRIAL_RESULT },
  { key: 'problem', label: 'Problem', type: 'textarea' },
  { key: 'evaluation', label: 'Evaluation', type: 'textarea' },
  { key: 'recommendation', label: 'Recommendation', type: 'textarea' },
];

const materialPreparationFields: FormFieldDef[] = [
  { key: 'materialReceived', label: 'Material Received', type: 'text', required: true },
  { key: 'batch', label: 'Batch', type: 'text' },
  { key: 'quantity', label: 'Quantity (kg)', type: 'number', required: true },
  { key: 'receivedDate', label: 'Received Date', type: 'date', required: true, prefill: 'today' },
  { key: 'supplier', label: 'Supplier', type: 'text', prefill: 'supplier' },
  { key: 'preparationDate', label: 'Preparation Date', type: 'date' },
  { key: 'pic', label: 'PIC', type: 'user', role: 'npd_staff', prefill: 'npdPic' },
];

const validationFields: FormFieldDef[] = [
  { key: 'validationDate', label: 'Validation Date', type: 'date', required: true, prefill: 'today' },
  { key: 'machine', label: 'Machine', type: 'text', required: true },
  { key: 'mold', label: 'Mold', type: 'text' },
  { key: 'cavity', label: 'Cavity', type: 'number' },
  { key: 'material', label: 'Material', type: 'text' },
  { key: 'productionQuantity', label: 'Production Quantity (pcs)', type: 'number', required: true },
  { key: 'parameter', label: 'Parameter', type: 'textarea' },
  { key: 'result', label: 'Result', type: 'textarea' },
  { key: 'problem', label: 'Problem', type: 'textarea' },
  { key: 'correctiveAction', label: 'Corrective Action', type: 'textarea' },
];

const customerDecision = (rejectTo: string, alternatives?: string[], approveTo?: string): ProcessOutcome[] => [
  {
    key: 'approved',
    label: 'Approved',
    tone: 'positive',
    target: approveTo ? { kind: 'process', key: approveTo } : { kind: 'next' },
    approvalStatus: 'approved',
  },
  {
    key: 'not_approved',
    label: 'Not Approved',
    tone: 'negative',
    target: { kind: 'process', key: rejectTo, alternatives },
    approvalStatus: 'rejected',
    requiresComment: true,
  },
];

const validationOutcomes: ProcessOutcome[] = [
  { key: 'pass', label: 'PASS', tone: 'positive', target: { kind: 'next' }, approvalStatus: 'approved' },
  { key: 'pass_condition', label: 'PASS WITH CONDITION', tone: 'neutral', target: { kind: 'next' }, approvalStatus: 'approved', requiresComment: true },
  { key: 'fail', label: 'FAIL', tone: 'negative', target: { kind: 'repeat' }, approvalStatus: 'rejected', requiresComment: true },
];

const materialPreparation = def({
  key: 'material_preparation',
  name: 'Material Preparation',
  description: 'Penerimaan dan persiapan material untuk validasi mass production.',
  picRole: 'npd_staff',
  actorRoles: ['npd_staff', 'purchasing'],
  uploadRoles: ['npd_staff', 'purchasing'],
  requiresDocument: true,
  requiredDocTypes: ['coa', 'material_spec'],
  suggestedDocTypes: ['coa', 'material_spec', 'supplier_document', 'other'],
  waitingType: 'external',
  waitingLabel: 'Supplier material',
  defaultNextAction: 'Follow up kedatangan material & siapkan COA',
  durationDays: 7,
  folder: '06 Material',
  recordType: 'material_preparation',
  fields: materialPreparationFields,
  calendarCategory: 'material_arrival',
});

const validation = def({
  key: 'validation_mass_production',
  name: 'Validation Mass Production',
  shortName: 'Validation',
  description: 'Validasi produksi massal. Result: PASS / FAIL / PASS WITH CONDITION.',
  kind: 'decision',
  picRole: 'npd_staff',
  actorRoles: ['npd_staff', 'quality', 'production'],
  uploadRoles: ['npd_staff', 'quality', 'production'],
  requiresDocument: true,
  requiredDocTypes: ['validation_report'],
  suggestedDocTypes: ['validation_report', 'trial_photo', 'other'],
  requiresApproval: true,
  approvalType: 'validation',
  approverType: 'internal',
  outcomes: validationOutcomes,
  defaultNextAction: 'Jalankan validasi mass production & upload report',
  durationDays: 5,
  folder: '09 Validation',
  recordType: 'validation',
  fields: validationFields,
  calendarCategory: 'validation',
});

const finish = def({
  key: 'finish',
  name: 'Finish',
  description: 'Project menjadi Completed hanya jika seluruh mandatory process selesai.',
  kind: 'finish',
  picRole: 'npd_staff',
  actorRoles: ['npd_staff'],
  uploadRoles: ['npd_staff'],
  defaultNextAction: 'Review kelengkapan & tutup project',
  durationDays: 1,
  folder: '09 Validation',
  fields: [{ key: 'closingNote', label: 'Catatan Penutupan', type: 'textarea' }],
});

export const SUBCONT_PROCESSES: ProcessDef[] = [
  def({
    key: 'npr',
    name: 'NPR',
    description: 'Admin Sales membuat dan mengirim New Product Request (NPR).',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    requiresDocument: true,
    requiredDocTypes: ['npr'],
    suggestedDocTypes: ['npr', 'customer_document'],
    defaultNextAction: 'Lengkapi data NPR & upload NPR Document',
    durationDays: 2,
    folder: '01 NPR',
    fields: requestFields('NPR Number'),
  }),
  def({
    key: 'npd_feedback',
    name: 'NPD Feedback NPR',
    shortName: 'NPD Feedback',
    description: 'NPD Staff memberi feedback, feasibility, risiko, dan rekomendasi.',
    kind: 'decision',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff'],
    uploadRoles: ['npd_staff'],
    suggestedDocTypes: ['feedback', 'technical_drawing'],
    requiresApproval: true,
    approvalType: 'npr',
    approverType: 'internal',
    outcomes: [
      { key: 'accepted', label: 'Accepted', tone: 'positive', target: { kind: 'next' }, approvalStatus: 'approved' },
      { key: 'need_revision', label: 'Need Revision', tone: 'neutral', target: { kind: 'process', key: 'npr' }, approvalStatus: 'revision_required', requiresComment: true },
      { key: 'need_info', label: 'Need More Information', tone: 'neutral', target: { kind: 'process', key: 'npr' }, approvalStatus: 'revision_required', requiresComment: true },
      { key: 'rejected', label: 'Rejected', tone: 'negative', target: { kind: 'cancel' }, approvalStatus: 'rejected', requiresComment: true },
    ],
    defaultNextAction: 'Berikan feedback & feasibility NPR',
    durationDays: 3,
    folder: '02 NPD Feedback',
    fields: feedbackFields,
  }),
  def({
    key: 'artwork',
    name: 'Artwork Development',
    shortName: 'Artwork',
    description: 'Drafter NPD membuat artwork (AI/PDF/EPS/SVG/PNG/JPG).',
    picRole: 'drafter',
    actorRoles: ['drafter'],
    uploadRoles: ['drafter', 'npd_staff'],
    requiresDocument: true,
    requiredDocTypes: ['artwork'],
    suggestedDocTypes: ['artwork', 'technical_drawing'],
    defaultNextAction: 'Selesaikan artwork & upload file',
    durationDays: 5,
    folder: '03 Artwork',
    fields: [
      { key: 'artworkName', label: 'Artwork Name', type: 'text', required: true },
      { key: 'product', label: 'Product', type: 'text', prefill: 'productName' },
      { key: 'size', label: 'Size', type: 'text', placeholder: 'mis. 50 x 120 mm' },
      { key: 'material', label: 'Material', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'printingMethod', label: 'Printing Method', type: 'select', options: ['Offset', 'Silk Screen', 'Hot Stamping', 'Heat Transfer', 'IML', 'Pad Printing', 'Digital Print'] },
      { key: 'decoration', label: 'Decoration', type: 'text' },
      { key: 'drafter', label: 'Drafter', type: 'user', role: 'drafter', prefill: 'drafter' },
      { key: 'deadline', label: 'Deadline', type: 'date' },
    ],
  }),
  def({
    key: 'sales_submit_artwork',
    name: 'Sales Submit Artwork',
    shortName: 'Submit Artwork',
    description: 'Sales mengirim artwork ke Customer. Status otomatis: Waiting Customer.',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales'],
    uploadRoles: ['admin_sales'],
    suggestedDocTypes: ['customer_document', 'other'],
    defaultNextAction: 'Submit artwork terbaru ke customer',
    durationDays: 1,
    folder: '04 Customer Approval',
    fields: [
      { key: 'submissionDate', label: 'Submission Date', type: 'date', required: true, prefill: 'today' },
      { key: 'salesPic', label: 'Sales PIC', type: 'user', role: 'admin_sales', prefill: 'salesPic', required: true },
      { key: 'customer', label: 'Customer', type: 'text', prefill: 'customer' },
      { key: 'artworkRevision', label: 'Artwork Revision', type: 'docRevision', docType: 'artwork', required: true },
      { key: 'submissionNote', label: 'Submission Note', type: 'textarea' },
    ],
  }),
  def({
    key: 'customer_artwork_approval',
    name: 'Customer Artwork Approval',
    shortName: 'Artwork Approval',
    description: 'Keputusan Customer via Sales. Not Approved → Artwork Revision → Sales Resubmit.',
    kind: 'decision',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales', 'npd_staff'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    suggestedDocTypes: ['approval', 'customer_document'],
    requiresApproval: true,
    approvalType: 'artwork',
    approverType: 'customer',
    waitingType: 'customer',
    outcomes: customerDecision('artwork'),
    defaultNextAction: 'Follow up customer approval',
    durationDays: 5,
    folder: '04 Customer Approval',
    calendarCategory: 'customer_approval',
  }),
  def({
    key: 'trial_material_prep',
    name: 'Trial Material Preparation',
    shortName: 'Trial Material',
    description: 'Persiapan material untuk trial: spesifikasi, supplier, batch, masterbatch.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'purchasing'],
    uploadRoles: ['npd_staff', 'purchasing'],
    requiresDocument: true,
    requiredDocTypes: ['material_spec', 'material_request'],
    suggestedDocTypes: ['material_spec', 'material_request', 'supplier_document', 'other'],
    defaultNextAction: 'Siapkan material trial & jadwalkan trial',
    durationDays: 5,
    folder: '06 Material',
    fields: [
      { key: 'material', label: 'Material', type: 'text', required: true },
      { key: 'materialType', label: 'Material Type', type: 'select', options: MATERIAL_TYPES },
      { key: 'supplier', label: 'Supplier', type: 'text', prefill: 'supplier' },
      { key: 'quantity', label: 'Quantity (kg)', type: 'number' },
      { key: 'batch', label: 'Batch', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'masterbatch', label: 'Masterbatch', type: 'text' },
      { key: 'trialRequirement', label: 'Trial Requirement', type: 'textarea' },
      { key: 'trialDate', label: 'Trial Date', type: 'date', required: true },
      { key: 'pic', label: 'PIC', type: 'user', role: 'npd_staff', prefill: 'npdPic' },
    ],
  }),
  def({
    key: 'trial_evaluation',
    name: 'Trial & Evaluation',
    shortName: 'Trial',
    description: 'Trial produksi dan evaluasi hasil (visual, dimension, leak, drop, dll).',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'production', 'quality'],
    uploadRoles: ['npd_staff', 'production', 'quality'],
    requiresDocument: true,
    requiredDocTypes: ['trial_report'],
    suggestedDocTypes: ['trial_report', 'trial_photo', 'trial_video'],
    defaultNextAction: 'Jalankan trial & upload trial report',
    durationDays: 4,
    folder: '05 Trial / T0',
    recordType: 'trial',
    fields: trialFields('Trial'),
    calendarCategory: 'trial',
  }),
  def({
    key: 'sales_submit_trial',
    name: 'Sales Submit Trial Result',
    shortName: 'Submit Trial',
    description: 'Sales mengirim hasil trial ke Customer.',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales'],
    uploadRoles: ['admin_sales'],
    suggestedDocTypes: ['trial_report', 'trial_photo', 'customer_document'],
    defaultNextAction: 'Kirim hasil trial ke customer',
    durationDays: 1,
    folder: '05 Trial / T0',
    fields: [
      { key: 'trialNumber', label: 'Trial Number', type: 'text' },
      { key: 'revision', label: 'Revision', type: 'text', placeholder: 'mis. Rev 00' },
      { key: 'submissionDate', label: 'Submission Date', type: 'date', required: true, prefill: 'today' },
      { key: 'salesPic', label: 'Sales PIC', type: 'user', role: 'admin_sales', prefill: 'salesPic', required: true },
      { key: 'customer', label: 'Customer', type: 'text', prefill: 'customer' },
      { key: 'trialResult', label: 'Trial Result', type: 'select', options: TRIAL_RESULT },
      { key: 'comment', label: 'Comment', type: 'textarea' },
    ],
  }),
  def({
    key: 'customer_trial_approval',
    name: 'Customer Trial Approval',
    shortName: 'Trial Approval',
    description: 'Keputusan Customer atas hasil trial. Not Approved → trial revision loop.',
    kind: 'decision',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales', 'npd_staff'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    suggestedDocTypes: ['approval', 'customer_document'],
    requiresApproval: true,
    approvalType: 'trial',
    approverType: 'customer',
    waitingType: 'customer',
    outcomes: customerDecision('trial_evaluation', ['trial_material_prep']),
    defaultNextAction: 'Follow up approval hasil trial ke customer',
    durationDays: 5,
    folder: '04 Customer Approval',
    calendarCategory: 'customer_approval',
  }),
  def({
    key: 'bulk_material_request',
    name: 'Bulk Material Request',
    shortName: 'Material Request',
    description: 'Permintaan material bulk ke Purchasing. Ref: FORM-NPD-12, SOP-PUR-03, SOP-PUR-01.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'purchasing'],
    uploadRoles: ['npd_staff', 'purchasing'],
    requiresDocument: true,
    requiredDocTypes: ['material_request'],
    suggestedDocTypes: ['material_request', 'material_spec'],
    defaultNextAction: 'Ajukan material request ke Purchasing',
    durationDays: 3,
    folder: '06 Material',
    recordType: 'material_request',
    fields: [
      { key: 'mrNumber', label: 'Material Request Number', type: 'text', required: true, helper: 'Form: FORM-NPD-12' },
      { key: 'material', label: 'Material', type: 'text', required: true },
      { key: 'supplier', label: 'Supplier', type: 'text', required: true, prefill: 'supplier' },
      { key: 'quantity', label: 'Quantity (kg)', type: 'number', required: true },
      { key: 'specification', label: 'Specification', type: 'textarea' },
      { key: 'requiredDate', label: 'Required Date', type: 'date', required: true },
      { key: 'purchasingPic', label: 'Purchasing PIC', type: 'user', role: 'purchasing' },
      { key: 'npdPic', label: 'NPD PIC', type: 'user', role: 'npd_staff', prefill: 'npdPic' },
      { key: 'requestDate', label: 'Request Date', type: 'date', prefill: 'today' },
    ],
  }),
  { ...materialPreparation },
  { ...validation },
  { ...finish },
];

export const NEW_MOLD_PROCESSES: ProcessDef[] = [
  def({
    key: 'project_request',
    name: 'Project Request',
    description: 'Request project new mold dari Customer melalui Sales.',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales', 'npd_staff'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    requiresDocument: true,
    requiredDocTypes: ['npr', 'customer_document'],
    suggestedDocTypes: ['npr', 'customer_document', 'technical_drawing'],
    defaultNextAction: 'Lengkapi project request & dokumen customer',
    durationDays: 2,
    folder: '01 NPR',
    fields: requestFields('Request Number'),
  }),
  def({
    key: 'npd_feedback',
    name: 'NPD Feedback',
    description: 'Feedback & feasibility, termasuk keputusan New Masterbatch (YES/NO).',
    kind: 'decision',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff'],
    uploadRoles: ['npd_staff'],
    suggestedDocTypes: ['feedback', 'technical_drawing'],
    requiresApproval: true,
    approvalType: 'npr',
    approverType: 'internal',
    outcomes: [
      { key: 'accepted_masterbatch', label: 'Accepted · New Masterbatch: YES', tone: 'positive', target: { kind: 'process', key: 'masterbatch_dev' }, approvalStatus: 'approved', setsNewMasterbatch: true },
      { key: 'accepted', label: 'Accepted · New Masterbatch: NO', tone: 'positive', target: { kind: 'process', key: 'prototype_3d' }, approvalStatus: 'approved', setsNewMasterbatch: false },
      { key: 'need_revision', label: 'Need Revision', tone: 'neutral', target: { kind: 'process', key: 'project_request' }, approvalStatus: 'revision_required', requiresComment: true },
      { key: 'rejected', label: 'Rejected', tone: 'negative', target: { kind: 'cancel' }, approvalStatus: 'rejected', requiresComment: true },
    ],
    defaultNextAction: 'Berikan feedback & tentukan New Masterbatch',
    durationDays: 3,
    folder: '02 NPD Feedback',
    fields: feedbackFields,
  }),
  def({
    key: 'masterbatch_dev',
    name: 'Masterbatch Development',
    shortName: 'Masterbatch',
    description: 'Pengembangan masterbatch/warna baru bersama supplier.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'purchasing'],
    uploadRoles: ['npd_staff', 'purchasing'],
    suggestedDocTypes: ['material_spec', 'supplier_document', 'trial_photo'],
    defaultNextAction: 'Kembangkan masterbatch bersama supplier',
    durationDays: 7,
    branchGroup: 'design',
    branch: 'masterbatch',
    folder: '06 Material',
    fields: [
      { key: 'masterbatchCode', label: 'Masterbatch Code', type: 'text', required: true },
      { key: 'colorTarget', label: 'Color Target', type: 'text', required: true, placeholder: 'mis. Pantone 7430 C' },
      { key: 'supplier', label: 'Supplier', type: 'text', prefill: 'supplier' },
      { key: 'letDownRatio', label: 'Let Down Ratio', type: 'text', placeholder: 'mis. 2%' },
      { key: 'result', label: 'Result', type: 'textarea' },
    ],
  }),
  def({
    key: 'masterbatch_approval',
    name: 'Customer Masterbatch Approval',
    shortName: 'MB Approval',
    description: 'Persetujuan Customer atas warna/masterbatch.',
    kind: 'decision',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales', 'npd_staff'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    suggestedDocTypes: ['approval', 'customer_document'],
    requiresApproval: true,
    approvalType: 'masterbatch',
    approverType: 'customer',
    waitingType: 'customer',
    outcomes: customerDecision('masterbatch_dev', undefined, 'drawing_2d'),
    defaultNextAction: 'Follow up approval masterbatch ke customer',
    durationDays: 4,
    branchGroup: 'design',
    branch: 'masterbatch',
    folder: '04 Customer Approval',
    calendarCategory: 'customer_approval',
  }),
  def({
    key: 'prototype_3d',
    name: '3D Prototype Development',
    shortName: '3D Prototype',
    description: 'Drafter membuat desain 3D dan prototype.',
    picRole: 'drafter',
    actorRoles: ['drafter'],
    uploadRoles: ['drafter', 'npd_staff'],
    requiresDocument: true,
    requiredDocTypes: ['drawing_3d'],
    suggestedDocTypes: ['drawing_3d', 'trial_photo'],
    defaultNextAction: 'Selesaikan 3D & prototype',
    durationDays: 6,
    branchGroup: 'design',
    branch: '3d',
    folder: '07 Mold / Drawing',
    fields: [
      { key: 'designName', label: 'Design Name', type: 'text', required: true },
      { key: 'prototypeMethod', label: 'Prototype Method', type: 'select', options: ['3D Print SLA', '3D Print FDM', 'CNC', 'Lainnya'] },
      { key: 'drafter', label: 'Drafter', type: 'user', role: 'drafter', prefill: 'drafter' },
      { key: 'notes', label: 'Catatan desain', type: 'textarea' },
    ],
  }),
  def({
    key: 'approval_3d',
    name: 'Customer 3D Approval',
    shortName: '3D Approval',
    description: 'Persetujuan Customer atas desain 3D/prototype.',
    kind: 'decision',
    picRole: 'admin_sales',
    actorRoles: ['admin_sales', 'npd_staff'],
    uploadRoles: ['admin_sales', 'npd_staff'],
    suggestedDocTypes: ['approval', 'customer_document'],
    requiresApproval: true,
    approvalType: '3d',
    approverType: 'customer',
    waitingType: 'customer',
    outcomes: customerDecision('prototype_3d'),
    defaultNextAction: 'Follow up approval 3D ke customer',
    durationDays: 4,
    branchGroup: 'design',
    branch: '3d',
    folder: '04 Customer Approval',
    calendarCategory: 'customer_approval',
  }),
  def({
    key: 'drawing_2d',
    name: '2D Drawing',
    description: 'Drafter membuat 2D drawing sebagai dasar mold drawing.',
    picRole: 'drafter',
    actorRoles: ['drafter'],
    uploadRoles: ['drafter', 'npd_staff'],
    requiresDocument: true,
    requiredDocTypes: ['drawing_2d'],
    suggestedDocTypes: ['drawing_2d', 'mold_drawing', 'technical_drawing'],
    defaultNextAction: 'Selesaikan 2D drawing',
    durationDays: 4,
    folder: '07 Mold / Drawing',
    fields: [
      { key: 'drawingNumber', label: 'Drawing Number', type: 'text', required: true },
      { key: 'criticalDimension', label: 'Critical Dimension / Tolerance', type: 'textarea' },
      { key: 'drafter', label: 'Drafter', type: 'user', role: 'drafter', prefill: 'drafter' },
    ],
  }),
  def({
    key: 'mold_drawing_approval',
    name: 'Mold Drawing Approval',
    shortName: 'Mold Drawing',
    description: 'Persetujuan mold drawing sebelum mold machining.',
    kind: 'decision',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'admin_sales'],
    uploadRoles: ['npd_staff', 'drafter', 'admin_sales'],
    suggestedDocTypes: ['mold_drawing', 'approval'],
    requiresApproval: true,
    approvalType: 'mold_drawing',
    approverType: 'customer',
    waitingType: 'customer',
    outcomes: customerDecision('drawing_2d'),
    defaultNextAction: 'Follow up approval mold drawing',
    durationDays: 4,
    folder: '07 Mold / Drawing',
    calendarCategory: 'customer_approval',
  }),
  def({
    key: 'mold_machining',
    name: 'Mold Machining',
    description: 'Pembuatan mold oleh Mold Maker.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff'],
    uploadRoles: ['npd_staff', 'purchasing'],
    suggestedDocTypes: ['supplier_document', 'mold_drawing', 'trial_photo'],
    waitingType: 'external',
    waitingLabel: 'Mold Maker',
    defaultNextAction: 'Monitor progress machining di mold maker',
    durationDays: 30,
    folder: '07 Mold / Drawing',
    fields: [
      { key: 'moldMaker', label: 'Mold Maker', type: 'text', required: true, prefill: 'supplier' },
      { key: 'poNumber', label: 'PO Number', type: 'text' },
      { key: 'progress', label: 'Progress (%)', type: 'number' },
      { key: 'notes', label: 'Catatan', type: 'textarea' },
    ],
  }),
  def({
    key: 't0_trial',
    name: 'T0 Trial & Evaluation',
    shortName: 'T0 Trial',
    description: 'Trial T0 mold baru. T0 Not OK → Mold Correction → Mold Machining → T0.',
    kind: 'decision',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'production', 'quality'],
    uploadRoles: ['npd_staff', 'production', 'quality'],
    requiresDocument: true,
    requiredDocTypes: ['trial_report'],
    suggestedDocTypes: ['trial_report', 'trial_photo', 'trial_video'],
    requiresApproval: true,
    approvalType: 't0',
    approverType: 'internal',
    outcomes: [
      { key: 't0_ok', label: 'T0 OK', tone: 'positive', target: { kind: 'process', key: 'mold_shipment' }, approvalStatus: 'approved' },
      { key: 't0_ng', label: 'T0 Not OK', tone: 'negative', target: { kind: 'process', key: 'mold_correction' }, approvalStatus: 'rejected', requiresComment: true },
    ],
    defaultNextAction: 'Jalankan T0 trial & evaluasi hasil',
    durationDays: 3,
    folder: '05 Trial / T0',
    recordType: 'trial',
    fields: trialFields('T0'),
    calendarCategory: 'trial',
  }),
  def({
    key: 'mold_correction',
    name: 'Mold Correction',
    description: 'Perbaikan mold setelah T0 Not OK. Setelah selesai kembali ke Mold Machining.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff'],
    uploadRoles: ['npd_staff'],
    isMandatory: false,
    loopOnly: true,
    nextKey: 'mold_machining',
    suggestedDocTypes: ['mold_drawing', 'supplier_document'],
    waitingType: 'external',
    waitingLabel: 'Mold Maker',
    defaultNextAction: 'Koordinasikan perbaikan mold dengan mold maker',
    durationDays: 10,
    folder: '07 Mold / Drawing',
    fields: [
      { key: 'correctionItems', label: 'Correction Items', type: 'textarea', required: true },
      { key: 'moldMaker', label: 'Mold Maker', type: 'text', prefill: 'supplier' },
      { key: 'estimatedFinish', label: 'Estimated Finish', type: 'date' },
    ],
  }),
  def({
    key: 'mold_shipment',
    name: 'Mold Shipment',
    description: 'Pengiriman mold dari mold maker ke pabrik.',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'purchasing'],
    uploadRoles: ['npd_staff', 'purchasing'],
    suggestedDocTypes: ['supplier_document', 'other'],
    waitingType: 'external',
    waitingLabel: 'Mold Maker',
    defaultNextAction: 'Konfirmasi jadwal pengiriman mold',
    durationDays: 5,
    folder: '07 Mold / Drawing',
    fields: [
      { key: 'shipmentDate', label: 'Shipment Date', type: 'date', required: true, prefill: 'today' },
      { key: 'deliveryNote', label: 'Delivery Note No.', type: 'text' },
      { key: 'receivedBy', label: 'Received By', type: 'text' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['Baik', 'Perlu Perbaikan'], required: true },
    ],
  }),
  def({
    key: 'commissioning_trial',
    name: 'Commissioning Trial',
    shortName: 'Commissioning',
    description: 'Trial commissioning mold di mesin produksi.',
    kind: 'decision',
    picRole: 'npd_staff',
    actorRoles: ['npd_staff', 'production', 'quality'],
    uploadRoles: ['npd_staff', 'production', 'quality'],
    requiresDocument: true,
    requiredDocTypes: ['trial_report'],
    suggestedDocTypes: ['trial_report', 'trial_photo', 'trial_video'],
    requiresApproval: true,
    approvalType: 'commissioning',
    approverType: 'internal',
    outcomes: [
      { key: 'ok', label: 'Commissioning OK', tone: 'positive', target: { kind: 'next' }, approvalStatus: 'approved' },
      { key: 'ng', label: 'Commissioning Not OK', tone: 'negative', target: { kind: 'repeat' }, approvalStatus: 'rejected', requiresComment: true },
    ],
    defaultNextAction: 'Jalankan commissioning trial',
    durationDays: 4,
    folder: '08 Commissioning',
    recordType: 'trial',
    fields: trialFields('Commissioning'),
    calendarCategory: 'commissioning',
  }),
  { ...materialPreparation },
  { ...validation },
  { ...finish },
];

export function defaultWorkflows(now: string): WorkflowTemplate[] {
  return [
    { id: 'wf-subcont', projectType: 'subcont', name: 'Subcont Workflow', version: 1, processes: SUBCONT_PROCESSES, updatedAt: now },
    { id: 'wf-new-mold', projectType: 'new_mold', name: 'New Mold Workflow', version: 1, processes: NEW_MOLD_PROCESSES, updatedAt: now },
  ];
}

/** Document folders shown in the Documents tab (PRD §8). */
export const DOCUMENT_FOLDERS = [
  '01 NPR',
  '02 NPD Feedback',
  '03 Artwork',
  '04 Customer Approval',
  '05 Trial / T0',
  '06 Material',
  '07 Mold / Drawing',
  '08 Commissioning',
  '09 Validation',
];
