-- =============================================================================
-- PIK MARKETING CONTROL — Database schema
-- PT Permata Indo Kemas
--
-- Target  : MySQL 5.7+ / MySQL 8.x / MariaDB 10.3+
-- Charset : utf8mb4 (utf8mb4_unicode_ci)
--
-- Aman dijalankan berulang: semua tabel memakai CREATE TABLE IF NOT EXISTS
-- (tidak ada DROP TABLE). Untuk mengosongkan database gunakan
-- `php database/import_workbook.php --fresh ...` (lihat README).
--
-- Konvensi:
--   id          : surrogate key INT (dipakai untuk relasi/foreign key)
--   code        : ID bisnis yang stabil (mis. CUS-894EA1DA5F) — sama dengan ID
--                 di PIK_Master_Database_AppSheet.xlsx untuk data hasil migrasi
--   source_file / source_sheet / legacy_row : jejak asal data spreadsheet
--   legacy_*    : nilai asli spreadsheet (disimpan untuk audit, tidak dipakai
--                 sebagai sumber perhitungan)
-- =============================================================================

SET NAMES utf8mb4;

-- -----------------------------------------------------------------------------
-- USERS & SECURITY
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                  VARCHAR(20)  NOT NULL,
  name                  VARCHAR(120) NOT NULL,
  email                 VARCHAR(190) NOT NULL,
  password_hash         VARCHAR(255) NOT NULL,
  role                  ENUM('Admin','Marketing','Sales','Management','PPIC','Viewer') NOT NULL DEFAULT 'Viewer',
  is_active             TINYINT(1)   NOT NULL DEFAULT 1,
  must_change_password  TINYINT(1)   NOT NULL DEFAULT 0,
  last_login_at         DATETIME     NULL,
  password_changed_at   DATETIME     NULL,
  created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_code (code),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_role (role, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS login_attempts (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email         VARCHAR(190) NOT NULL,
  ip_address    VARCHAR(45)  NOT NULL,
  success       TINYINT(1)   NOT NULL DEFAULT 0,
  attempted_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_login_email (email, attempted_at),
  KEY idx_login_ip (ip_address, attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  setting_key    VARCHAR(100) NOT NULL,
  setting_value  TEXT         NULL,
  updated_at     DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- CUSTOMER
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
  id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code              VARCHAR(20)  NOT NULL,
  name              VARCHAR(190) NOT NULL,
  company           VARCHAR(190) NULL,
  pic               VARCHAR(120) NULL COMMENT 'Contact person di sisi customer',
  phone             VARCHAR(40)  NULL,
  email             VARCHAR(190) NULL,
  address           TEXT         NULL,
  industry          VARCHAR(100) NULL,
  status            ENUM('Active','Inactive','Potential','Dormant') NOT NULL DEFAULT 'Active',
  source            VARCHAR(100) NULL,
  marketing_pic_id  INT UNSIGNED NULL COMMENT 'PIC internal (users.id)',
  notes             TEXT         NULL,
  created_by        INT UNSIGNED NULL,
  updated_by        INT UNSIGNED NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customers_code (code),
  KEY idx_customers_name (name),
  KEY idx_customers_status (status),
  KEY idx_customers_pic (marketing_pic_id),
  CONSTRAINT fk_customers_pic     FOREIGN KEY (marketing_pic_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_customers_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_customers_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contacts (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code         VARCHAR(20)  NOT NULL,
  customer_id  INT UNSIGNED NOT NULL,
  name         VARCHAR(150) NOT NULL,
  position     VARCHAR(100) NULL,
  phone        VARCHAR(40)  NULL,
  whatsapp     VARCHAR(40)  NULL,
  email        VARCHAR(190) NULL,
  is_primary   TINYINT(1)   NOT NULL DEFAULT 0,
  status       ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  notes        TEXT         NULL,
  created_by   INT UNSIGNED NULL,
  updated_by   INT UNSIGNED NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_contacts_code (code),
  KEY idx_contacts_customer (customer_id),
  KEY idx_contacts_name (name),
  CONSTRAINT fk_contacts_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
  CONSTRAINT fk_contacts_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_contacts_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- PRODUCTS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code              VARCHAR(20)  NOT NULL,
  name              VARCHAR(190) NOT NULL,
  product_code      VARCHAR(60)  NULL COMMENT 'Kode produk legacy, mis. [BTNEA80] (tidak unik)',
  variant           VARCHAR(255) NULL,
  spec              TEXT         NULL COMMENT 'Spesifikasi terakhir dari OEF',
  category          VARCHAR(100) NULL,
  capacity_per_day  INT UNSIGNED NULL,
  unit              VARCHAR(20)  NOT NULL DEFAULT 'pcs',
  is_active         TINYINT(1)   NOT NULL DEFAULT 1,
  source            VARCHAR(50)  NULL,
  notes             TEXT         NULL,
  created_by        INT UNSIGNED NULL,
  updated_by        INT UNSIGNED NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_code (code),
  KEY idx_products_name (name),
  KEY idx_products_pcode (product_code),
  CONSTRAINT fk_products_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_products_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- CRM: LEADS, ACTIVITIES, FOLLOW UP
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id                   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                 VARCHAR(20)  NOT NULL,
  customer_id          INT UNSIGNED NULL,
  lead_name            VARCHAR(190) NOT NULL,
  company_name         VARCHAR(190) NULL COMMENT 'Nama perusahaan prospek bila belum menjadi customer',
  contact_name         VARCHAR(120) NULL,
  phone                VARCHAR(40)  NULL,
  email                VARCHAR(190) NULL,
  source               VARCHAR(100) NULL,
  product_interest     VARCHAR(255) NULL,
  estimated_qty        INT UNSIGNED NULL,
  potential_value      DECIMAL(18,2) NULL,
  expected_close_date  DATE         NULL,
  status               ENUM('New','Contacted','Qualified','Quotation','Negotiation','Won','Lost','Dormant') NOT NULL DEFAULT 'New',
  priority             ENUM('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  pic_user_id          INT UNSIGNED NULL,
  next_follow_up       DATE         NULL,
  last_contact         DATE         NULL,
  status_changed_at    DATETIME     NULL,
  notes                TEXT         NULL,
  created_by           INT UNSIGNED NULL,
  updated_by           INT UNSIGNED NULL,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_leads_code (code),
  KEY idx_leads_status (status),
  KEY idx_leads_customer (customer_id),
  KEY idx_leads_pic (pic_user_id),
  KEY idx_leads_created (created_at),
  CONSTRAINT fk_leads_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_leads_pic      FOREIGN KEY (pic_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activities (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code            VARCHAR(20)  NOT NULL,
  customer_id     INT UNSIGNED NULL,
  lead_id         INT UNSIGNED NULL,
  activity_date   DATETIME     NOT NULL,
  activity_type   ENUM('WhatsApp','Phone Call','Email','Meeting','Visit','Quotation','Sample','Presentation','Follow Up','Complaint','Other') NOT NULL,
  pic_user_id     INT UNSIGNED NULL,
  subject         VARCHAR(190) NOT NULL,
  description     TEXT         NULL,
  next_action     VARCHAR(255) NULL,
  next_follow_up  DATE         NULL,
  attachment      VARCHAR(500) NULL COMMENT 'Link dokumen (mis. Google Drive)',
  created_by      INT UNSIGNED NULL,
  updated_by      INT UNSIGNED NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_activities_code (code),
  KEY idx_activities_customer (customer_id, activity_date),
  KEY idx_activities_lead (lead_id),
  KEY idx_activities_date (activity_date),
  KEY idx_activities_pic (pic_user_id),
  CONSTRAINT fk_activities_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_activities_lead     FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE RESTRICT,
  CONSTRAINT fk_activities_pic      FOREIGN KEY (pic_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_activities_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_activities_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS follow_up (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code             VARCHAR(20)  NOT NULL,
  customer_id      INT UNSIGNED NULL,
  lead_id          INT UNSIGNED NULL,
  activity_id      INT UNSIGNED NULL COMMENT 'Activity asal (bila dibuat otomatis)',
  pic_user_id      INT UNSIGNED NULL,
  follow_up_date   DATE         NOT NULL,
  follow_up_time   TIME         NULL,
  follow_up_type   ENUM('WhatsApp','Phone Call','Email','Meeting','Visit','Quotation','Sample','Presentation','Follow Up','Complaint','Other') NOT NULL DEFAULT 'Follow Up',
  purpose          VARCHAR(255) NOT NULL,
  status           ENUM('Planned','Done','Reschedule','Cancelled','Overdue') NOT NULL DEFAULT 'Planned',
  result           TEXT         NULL,
  next_follow_up   DATE         NULL,
  reminder         TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '1 = kirim notifikasi ke PIC',
  notes            TEXT         NULL,
  completed_at     DATETIME     NULL,
  created_by       INT UNSIGNED NULL,
  updated_by       INT UNSIGNED NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_follow_up_code (code),
  KEY idx_follow_up_date_status (follow_up_date, status),
  KEY idx_follow_up_customer (customer_id),
  KEY idx_follow_up_lead (lead_id),
  KEY idx_follow_up_pic (pic_user_id),
  CONSTRAINT fk_follow_up_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_follow_up_lead     FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE RESTRICT,
  CONSTRAINT fk_follow_up_activity FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE SET NULL,
  CONSTRAINT fk_follow_up_pic      FOREIGN KEY (pic_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_follow_up_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_follow_up_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- OPERATIONS: ORDER ENTRY FORM (purchase_orders + po_lines), DELIVERIES,
--             COMPLAINT & RETURN
-- Tabel purchase_orders menyimpan Order Entry Form (OEF). Data PO lama tetap
-- di tabel yang sama (order_number & ppic_status NULL).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
  id                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                  VARCHAR(20)  NOT NULL,
  order_number          VARCHAR(30)  NULL COMMENT 'No. Order Entry Form (OEF-YYMM-NNNN)',
  po_number             VARCHAR(80)  NULL COMMENT 'No. PO dari customer',
  customer_id           INT UNSIGNED NULL COMMENT 'NULL hanya untuk data legacy yang customer-nya tidak ditemukan',
  sales_name            VARCHAR(120) NULL,
  sales_user_id         INT UNSIGNED NULL,
  po_date               DATE         NULL COMMENT 'Tanggal order',
  payment_term          VARCHAR(60)  NULL,
  product_spec          TEXT         NULL,
  is_subcont            TINYINT(1)   NOT NULL DEFAULT 0,
  supplier              VARCHAR(190) NULL,
  requested_date        DATE         NULL COMMENT 'Permintaan selesai / kirim',
  ship_to               VARCHAR(255) NULL COMMENT 'Tujuan kirim',
  status                ENUM('Open','On Process','Partial','Closed','Cancelled') NOT NULL DEFAULT 'Open',
  ppic_status           ENUM('Pending','Approved','Rejected') NULL COMMENT 'NULL = data lama (tanpa konfirmasi PPIC)',
  ppic_note             TEXT         NULL,
  ppic_by               INT UNSIGNED NULL,
  ppic_at               DATETIME     NULL,
  schedule_delivery_id  INT UNSIGNED NULL COMMENT 'Jadwal delivery otomatis dari OEF (FK ditambahkan oleh migrator)',
  legacy_status         VARCHAR(40)  NULL,
  remark         TEXT         NULL,
  source_file    VARCHAR(255) NULL,
  source_sheet   VARCHAR(100) NULL,
  legacy_row     INT          NULL,
  created_by     INT UNSIGNED NULL,
  updated_by     INT UNSIGNED NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_po_code (code),
  KEY idx_po_number (po_number),
  KEY idx_po_customer (customer_id, po_date),
  KEY idx_po_status (status),
  KEY idx_po_date (po_date),
  UNIQUE KEY uq_po_order_number (order_number),
  KEY idx_po_ppic (ppic_status),
  CONSTRAINT fk_po_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_po_sales    FOREIGN KEY (sales_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_po_ppic_by  FOREIGN KEY (ppic_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_po_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_po_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS po_lines (
  id                      INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                    VARCHAR(20)  NOT NULL,
  po_id                   INT UNSIGNED NOT NULL,
  product_id              INT UNSIGNED NOT NULL,
  product_name_legacy     VARCHAR(255) NULL,
  variant_legacy          VARCHAR(255) NULL,
  order_qty               INT          NOT NULL,
  capacity_per_day        INT UNSIGNED NULL,
  remark                  TEXT         NULL,
  legacy_delivered_qty    INT          NULL COMMENT 'DeliveredQuantitySource (spreadsheet)',
  legacy_return_qty       INT          NULL COMMENT 'ReturnQuantitySource (spreadsheet)',
  legacy_outstanding_qty  INT          NULL COMMENT 'OutstandingSource (spreadsheet)',
  legacy_status           VARCHAR(40)  NULL,
  source_file             VARCHAR(255) NULL,
  source_sheet            VARCHAR(100) NULL,
  legacy_row              INT          NULL,
  created_by              INT UNSIGNED NULL,
  updated_by              INT UNSIGNED NULL,
  created_at              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_po_lines_code (code),
  KEY idx_po_lines_po (po_id),
  KEY idx_po_lines_product (product_id),
  CONSTRAINT fk_po_lines_po      FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_po_lines_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_po_lines_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_po_lines_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deliveries (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code            VARCHAR(20)  NOT NULL,
  po_id           INT UNSIGNED NULL,
  po_line_id      INT UNSIGNED NULL COMMENT 'Wajib untuk data baru; NULL = legacy belum terhubung (lihat migration_issues)',
  product_id      INT UNSIGNED NULL,
  delivery_date   DATE         NULL,
  sj_number       VARCHAR(60)  NULL COMMENT 'Nomor Surat Jalan',
  destination     VARCHAR(255) NULL,
  delivered_qty   INT          NULL,
  status          ENUM('Scheduled','On Delivery','Delivered','Partial','Cancelled') NOT NULL DEFAULT 'Scheduled',
  note            TEXT         NULL,
  attachment      VARCHAR(500) NULL,
  migration_flag  VARCHAR(40)  NULL,
  source_file     VARCHAR(255) NULL,
  source_sheet    VARCHAR(100) NULL,
  legacy_row      INT          NULL,
  created_by      INT UNSIGNED NULL,
  updated_by      INT UNSIGNED NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_deliveries_code (code),
  KEY idx_deliveries_po (po_id),
  KEY idx_deliveries_line (po_line_id, status),
  KEY idx_deliveries_product (product_id),
  KEY idx_deliveries_date (delivery_date),
  KEY idx_deliveries_status (status, delivery_date),
  KEY idx_deliveries_sj (sj_number),
  CONSTRAINT fk_deliveries_po      FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_deliveries_line    FOREIGN KEY (po_line_id) REFERENCES po_lines (id) ON DELETE RESTRICT,
  CONSTRAINT fk_deliveries_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_deliveries_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_deliveries_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS returns (
  id                 INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code               VARCHAR(20)  NOT NULL,
  record_type        ENUM('Complaint','Return') NOT NULL DEFAULT 'Return' COMMENT 'Complaint = tanpa barang kembali',
  customer_id        INT UNSIGNED NULL,
  po_id              INT UNSIGNED NULL,
  po_line_id         INT UNSIGNED NULL COMMENT 'Wajib untuk data baru; NULL = legacy belum terhubung',
  product_id         INT UNSIGNED NULL,
  delivery_id        INT UNSIGNED NULL COMMENT 'Delivery/Surat Jalan asal (opsional)',
  return_date        DATE         NULL,
  sj_number          VARCHAR(60)  NULL,
  destination        VARCHAR(255) NULL,
  return_qty         INT          NULL,
  reason             ENUM('Damage','Wrong Product','Quality Issue','Over Delivery','Customer Request','Other') NULL,
  complaint_detail   TEXT         NULL,
  complaint_status   ENUM('Open','Resolved','Unresolved') NOT NULL DEFAULT 'Open',
  resolution_note    TEXT         NULL COMMENT 'Hasil penyelesaian / alasan tidak selesai',
  resolved_by        INT UNSIGNED NULL,
  resolved_at        DATETIME     NULL,
  qc_email           VARCHAR(500) NULL COMMENT 'Email QC penerima notifikasi (pisahkan dengan koma)',
  email_status       VARCHAR(20)  NULL,
  email_sent_at      DATETIME     NULL,
  email_error        VARCHAR(500) NULL,
  attachment         VARCHAR(500) NULL,
  note               TEXT         NULL,
  po_number_legacy   VARCHAR(80)  NULL,
  product_legacy     VARCHAR(255) NULL,
  source_file        VARCHAR(255) NULL,
  source_sheet       VARCHAR(100) NULL,
  legacy_row         INT          NULL,
  created_by         INT UNSIGNED NULL,
  updated_by         INT UNSIGNED NULL,
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_returns_code (code),
  KEY idx_returns_po (po_id),
  KEY idx_returns_line (po_line_id),
  KEY idx_returns_product (product_id),
  KEY idx_returns_date (return_date),
  KEY idx_returns_customer (customer_id),
  KEY idx_returns_complaint (complaint_status, return_date),
  CONSTRAINT fk_returns_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_returns_resolved FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_returns_po       FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_returns_line     FOREIGN KEY (po_line_id) REFERENCES po_lines (id) ON DELETE RESTRICT,
  CONSTRAINT fk_returns_product  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_returns_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id) ON DELETE SET NULL,
  CONSTRAINT fk_returns_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_returns_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS complaint_attachments (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  return_id      INT UNSIGNED NOT NULL,
  original_name  VARCHAR(190) NOT NULL,
  stored_name    VARCHAR(120) NOT NULL COMMENT 'File di storage/uploads/complaints/<return_id>/',
  mime_type      VARCHAR(80)  NOT NULL,
  file_size      INT UNSIGNED NOT NULL,
  uploaded_by    INT UNSIGNED NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_complaint_att_return (return_id),
  CONSTRAINT fk_complaint_att_return FOREIGN KEY (return_id) REFERENCES returns (id) ON DELETE CASCADE,
  CONSTRAINT fk_complaint_att_user   FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- INVENTORY: STOCK, LEAD TIME, INBOUND MAKLON
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code            VARCHAR(20)  NOT NULL,
  product_id      INT UNSIGNED NULL COMMENT 'NULL = legacy belum terhubung ke master produk',
  product_legacy  VARCHAR(255) NULL,
  stock_type      ENUM('FG','WIP','Ready','Reserved') NOT NULL,
  quantity        INT          NULL,
  box             INT          NULL,
  qty_per_box     INT          NULL,
  status          VARCHAR(40)  NULL,
  notes           TEXT         NULL,
  source_file     VARCHAR(255) NULL,
  source_sheet    VARCHAR(100) NULL,
  legacy_row      INT          NULL,
  created_by      INT UNSIGNED NULL,
  updated_by      INT UNSIGNED NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_code (code),
  KEY idx_stock_product (product_id, stock_type),
  KEY idx_stock_type (stock_type),
  CONSTRAINT fk_stock_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_stock_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_stock_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leadtime (
  id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code              VARCHAR(20)  NOT NULL,
  po_id             INT UNSIGNED NULL,
  product_id        INT UNSIGNED NULL,
  po_number_legacy  VARCHAR(80)  NULL,
  product_legacy    VARCHAR(255) NULL,
  quantity          INT          NULL,
  delivery_date     DATE         NULL COMMENT 'Estimasi tanggal delivery',
  status            ENUM('Planned','On Process','Delivered','Delayed','Cancelled') NOT NULL DEFAULT 'Planned',
  legacy_status     VARCHAR(40)  NULL,
  notes             TEXT         NULL,
  source_file       VARCHAR(255) NULL,
  source_sheet      VARCHAR(100) NULL,
  legacy_row        INT          NULL,
  created_by        INT UNSIGNED NULL,
  updated_by        INT UNSIGNED NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_leadtime_code (code),
  KEY idx_leadtime_po (po_id),
  KEY idx_leadtime_product (product_id),
  KEY idx_leadtime_date (delivery_date),
  CONSTRAINT fk_leadtime_po      FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_leadtime_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_leadtime_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_leadtime_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inbound_maklon (
  id                       INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code                     VARCHAR(20)  NOT NULL,
  vendor                   VARCHAR(120) NULL,
  receiver                 VARCHAR(120) NULL,
  actual_inbound_date      DATE         NULL,
  sj_date                  DATE         NULL,
  sj_number                VARCHAR(60)  NULL,
  po_id                    INT UNSIGNED NULL,
  po_number_legacy         VARCHAR(80)  NULL,
  product_id               INT UNSIGNED NULL,
  internal_component_code  VARCHAR(60)  NULL,
  type                     VARCHAR(60)  NULL,
  component_name           VARCHAR(255) NULL,
  factory_component_code   VARCHAR(60)  NULL,
  quantity                 INT          NULL,
  reject_qty               INT          NULL,
  total_in                 INT          NULL,
  attachment               VARCHAR(500) NULL,
  notes                    TEXT         NULL,
  odoo_checklist           VARCHAR(60)  NULL,
  source_file              VARCHAR(255) NULL,
  source_sheet             VARCHAR(100) NULL,
  legacy_row               INT          NULL,
  created_by               INT UNSIGNED NULL,
  updated_by               INT UNSIGNED NULL,
  created_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inbound_code (code),
  KEY idx_inbound_po (po_id),
  KEY idx_inbound_product (product_id),
  KEY idx_inbound_date (actual_inbound_date),
  CONSTRAINT fk_inbound_po      FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_inbound_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_inbound_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_inbound_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- FINANCE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoices_payments (
  id                              INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  code                            VARCHAR(20)   NOT NULL,
  customer_id                     INT UNSIGNED  NULL,
  po_id                           INT UNSIGNED  NULL,
  po_number_legacy                VARCHAR(80)   NULL,
  invoice_number                  VARCHAR(80)   NULL,
  invoice_date                    DATE          NULL,
  due_date                        DATE          NULL,
  invoice_amount                  DECIMAL(18,2) NOT NULL DEFAULT 0,
  paid_amount                     DECIMAL(18,2) NOT NULL DEFAULT 0,
  payment_date                    DATE          NULL COMMENT 'Tanggal pembayaran terakhir',
  payment_receipt_number          VARCHAR(80)   NULL,
  status                          ENUM('Unpaid','Partial','Paid','Overdue') NOT NULL DEFAULT 'Unpaid',
  legacy_invoice_outstanding      DECIMAL(18,2) NULL,
  legacy_cumulative_outstanding   DECIMAL(18,2) NULL,
  invoice_attachment              VARCHAR(500)  NULL,
  payment_attachment              VARCHAR(500)  NULL,
  notes                           TEXT          NULL,
  source_file                     VARCHAR(255)  NULL,
  source_sheet                    VARCHAR(100)  NULL,
  legacy_row                      INT           NULL,
  created_by                      INT UNSIGNED  NULL,
  updated_by                      INT UNSIGNED  NULL,
  created_at                      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                      DATETIME      NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoices_code (code),
  UNIQUE KEY uq_invoices_number (invoice_number),
  KEY idx_invoices_customer (customer_id),
  KEY idx_invoices_po (po_id),
  KEY idx_invoices_status (status),
  KEY idx_invoices_date (invoice_date),
  KEY idx_invoices_due (due_date),
  CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_po       FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_created  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_invoices_updated  FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS po_financials (
  id                   INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  code                 VARCHAR(20)   NOT NULL,
  po_id                INT UNSIGNED  NULL,
  po_number_legacy     VARCHAR(80)   NULL,
  brand                VARCHAR(100)  NULL,
  po_date              DATE          NULL,
  product_legacy       VARCHAR(255)  NULL,
  product_code_legacy  VARCHAR(60)   NULL,
  order_qty            INT           NULL,
  unit_price           DECIMAL(18,6) NULL,
  total_order_amount   DECIMAL(18,2) NULL,
  ppn                  DECIMAL(18,2) NULL,
  total_incl_ppn       DECIMAL(18,2) NULL,
  delivered_qty        INT           NULL,
  undelivered_qty      INT           NULL,
  outstanding_amount   DECIMAL(18,2) NULL,
  payment_status       ENUM('Unpaid','Partial','Paid') NULL,
  legacy_status        VARCHAR(40)   NULL,
  attachment           VARCHAR(500)  NULL,
  notes                TEXT          NULL,
  source_file          VARCHAR(255)  NULL,
  source_sheet         VARCHAR(100)  NULL,
  legacy_row           INT           NULL,
  created_by           INT UNSIGNED  NULL,
  updated_by           INT UNSIGNED  NULL,
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME      NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_po_financials_code (code),
  KEY idx_po_financials_po (po_id),
  CONSTRAINT fk_po_financials_po      FOREIGN KEY (po_id) REFERENCES purchase_orders (id) ON DELETE RESTRICT,
  CONSTRAINT fk_po_financials_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_po_financials_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- NOTIFICATIONS, AUDIT LOG, MIGRATION ISSUES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id      INT UNSIGNED NOT NULL,
  type         VARCHAR(40)  NOT NULL,
  title        VARCHAR(190) NOT NULL,
  message      VARCHAR(500) NULL,
  link         VARCHAR(255) NULL,
  entity_type  VARCHAR(40)  NULL,
  entity_id    INT UNSIGNED NULL,
  dedupe_key   VARCHAR(120) NULL,
  is_read      TINYINT(1)   NOT NULL DEFAULT 0,
  read_at      DATETIME     NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_notifications_dedupe (user_id, dedupe_key),
  KEY idx_notifications_user (user_id, is_read, created_at),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id       INT UNSIGNED NULL,
  user_name     VARCHAR(120) NULL COMMENT 'Snapshot nama user saat aksi',
  action        VARCHAR(40)  NOT NULL,
  entity_type   VARCHAR(40)  NULL,
  entity_id     INT UNSIGNED NULL,
  entity_label  VARCHAR(190) NULL,
  changes       LONGTEXT     NULL COMMENT 'JSON: {"field": {"old": ..., "new": ...}}',
  ip_address    VARCHAR(45)  NULL,
  user_agent    VARCHAR(255) NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_entity (entity_type, entity_id),
  KEY idx_audit_user (user_id, created_at),
  KEY idx_audit_created (created_at),
  KEY idx_audit_action (action),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS migration_issues (
  id                 INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code               VARCHAR(20)  NOT NULL,
  table_name         VARCHAR(40)  NOT NULL,
  record_code        VARCHAR(20)  NULL,
  record_id          INT UNSIGNED NULL,
  issue_type         VARCHAR(60)  NOT NULL,
  field_name         VARCHAR(60)  NULL,
  master_value       VARCHAR(255) NULL COMMENT 'Nilai di master workbook',
  suggested_value    VARCHAR(255) NULL COMMENT 'Nilai usulan (mis. dari file legacy)',
  legacy_po          VARCHAR(120) NULL,
  legacy_product     VARCHAR(255) NULL,
  description        TEXT         NULL,
  source_file        VARCHAR(255) NULL,
  source_sheet       VARCHAR(100) NULL,
  legacy_row         INT          NULL,
  resolution_status  ENUM('Needs Review','Auto-Corrected','Resolved','Ignored') NOT NULL DEFAULT 'Needs Review',
  resolution_note    TEXT         NULL,
  resolved_by        INT UNSIGNED NULL,
  resolved_at        DATETIME     NULL,
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_migration_issues_code (code),
  KEY idx_mi_record (table_name, record_id),
  KEY idx_mi_status (resolution_status, issue_type),
  CONSTRAINT fk_mi_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
