"""Template workflow default (PRD §4 Subcont dan §5 New Mold).

Setiap proses adalah dictionary. Kunci penting:
- key / name / short_name    : identitas proses
- kind                        : "task" (dikerjakan lalu selesai), "decision" (punya pilihan hasil),
                                "finish" (penutupan project)
- pic_role / actor_roles      : role PIC default & role yang boleh mengerjakan
- requires_document / required_doc_types : dokumen wajib sebelum proses bisa diselesaikan
- outcomes                    : pilihan hasil untuk proses decision, beserta tujuan workflow:
      target = {"kind": "next"}                   -> lanjut ke proses berikutnya
      target = {"kind": "process", "key": "..."}  -> lompat ke proses tertentu
                 (jika proses tujuan ada di belakang = revision loop)
      target = {"kind": "repeat"}                 -> ulangi proses ini (status Problem)
      target = {"kind": "cancel"}                 -> project dibatalkan
- fields                      : isian form proses (lihat templates/projects/process_complete.html)

Admin dapat mengubah template lewat menu Pengaturan -> Workflow. Project yang sudah
berjalan tetap memakai salinan (snapshot) template versi saat project dibuat.
"""
from copy import deepcopy

TESTS = ["Visual", "Dimension", "Weight", "Leak", "Drop", "Vacuum", "Assembly", "Function", "Appearance", "Color", "Printing", "Lainnya"]
TRIAL_RESULT = ["OK", "OK dengan catatan", "NG"]
MATERIAL_TYPES = ["PP", "PE", "HDPE", "LDPE", "PET", "PETG", "ABS", "AS", "PCR", "Lainnya"]


def define(**kw) -> dict:
    """Membuat definisi proses dengan nilai default."""
    base = {
        "short_name": kw["name"],
        "description": "",
        "kind": "task",
        "actor_roles": [kw["pic_role"]],
        "upload_roles": kw.get("actor_roles", [kw["pic_role"]]),
        "is_mandatory": True,
        "loop_only": False,
        "requires_document": False,
        "required_doc_types": [],
        "suggested_doc_types": kw.get("required_doc_types", []),
        "requires_approval": False,
        "approval_type": None,
        "approver_type": None,
        "outcomes": [],
        "next_key": None,
        "waiting_type": "internal",
        "waiting_label": None,
        "default_next_action": f"Selesaikan {kw['name']}",
        "duration_days": 3,
        "branch_group": None,
        "branch": None,
        "folder": "Lainnya",
        "record_type": "general",
        "fields": [],
        "calendar_category": None,
        "custom": False,
    }
    base.update(kw)
    return base


def field(key, label, type="text", required=False, **kw) -> dict:
    """Satu isian form. type: text | textarea | number | date | select | multiselect | user | doc_revision."""
    return {"key": key, "label": label, "type": type, "required": required, **kw}


def request_fields(number_label):
    return [
        field("request_number", number_label, required=True, placeholder="mis. NPR-2026-014"),
        field("customer", "Customer", required=True, prefill="customer"),
        field("project_name", "Project Name", required=True, prefill="project_name"),
        field("product", "Product", required=True, prefill="product_name"),
        field("request_date", "Request Date", "date", required=True, prefill="today"),
        field("customer_request", "Customer Request", "textarea", required=True, prefill="customer_request"),
        field("quantity", "Quantity (pcs)", "number", required=True),
        field("material", "Material", required=True),
        field("color", "Color"),
        field("specification", "Specification", "textarea"),
        field("target_date", "Target Date", "date"),
        field("sales_pic", "Sales PIC", "user", required=True, role="admin_sales", prefill="sales_pic"),
    ]


FEEDBACK_FIELDS = [
    field("feedback", "Feedback", "textarea", required=True),
    field("feasibility", "Feasibility", "select", required=True, options=["Feasible", "Feasible dengan catatan", "Not Feasible"]),
    field("technical_notes", "Technical Notes", "textarea"),
    field("estimated_timeline", "Estimated Timeline", placeholder="mis. 6 minggu"),
    field("required_information", "Required Information", "textarea"),
    field("risk", "Risk", "textarea"),
    field("recommendation", "Recommendation", "textarea"),
]


def trial_fields(prefix):
    return [
        field("trial_number", f"{prefix} Number", helper="Kosongkan untuk nomor otomatis"),
        field("trial_date", f"{prefix} Date", "date", required=True, prefill="today"),
        field("machine", "Machine", required=True),
        field("mold", "Mold"),
        field("cavity", "Cavity", "number"),
        field("material", "Material"),
        field("parameter", "Parameter", "textarea"),
        field("quantity", "Quantity (pcs)", "number"),
        field("tests", "Test", "multiselect", options=TESTS),
        field("trial_result", f"{prefix} Result", "select", required=True, options=TRIAL_RESULT),
        field("problem", "Problem", "textarea"),
        field("evaluation", "Evaluation", "textarea"),
        field("recommendation", "Recommendation", "textarea"),
    ]


def customer_decision(reject_to, alternatives=None, approve_to=None):
    return [
        {
            "key": "approved",
            "label": "Approved",
            "tone": "positive",
            "target": {"kind": "process", "key": approve_to} if approve_to else {"kind": "next"},
            "approval_status": "approved",
        },
        {
            "key": "not_approved",
            "label": "Not Approved",
            "tone": "negative",
            "target": {"kind": "process", "key": reject_to, "alternatives": alternatives or []},
            "approval_status": "rejected",
            "requires_comment": True,
        },
    ]


VALIDATION_OUTCOMES = [
    {"key": "pass", "label": "PASS", "tone": "positive", "target": {"kind": "next"}, "approval_status": "approved"},
    {"key": "pass_condition", "label": "PASS WITH CONDITION", "tone": "neutral", "target": {"kind": "next"}, "approval_status": "approved", "requires_comment": True},
    {"key": "fail", "label": "FAIL", "tone": "negative", "target": {"kind": "repeat"}, "approval_status": "rejected", "requires_comment": True},
]

MATERIAL_PREPARATION = define(
    key="material_preparation",
    name="Material Preparation",
    description="Penerimaan dan persiapan material untuk validasi mass production.",
    pic_role="npd_staff",
    actor_roles=["npd_staff", "purchasing"],
    upload_roles=["npd_staff", "purchasing"],
    requires_document=True,
    required_doc_types=["coa", "material_spec"],
    suggested_doc_types=["coa", "material_spec", "supplier_document", "other"],
    waiting_type="external",
    waiting_label="Supplier material",
    default_next_action="Follow up kedatangan material & siapkan COA",
    duration_days=7,
    folder="06 Material",
    record_type="material_preparation",
    calendar_category="material_arrival",
    fields=[
        field("material_received", "Material Received", required=True),
        field("batch", "Batch"),
        field("quantity", "Quantity (kg)", "number", required=True),
        field("received_date", "Received Date", "date", required=True, prefill="today"),
        field("supplier", "Supplier", prefill="supplier"),
        field("preparation_date", "Preparation Date", "date"),
        field("pic", "PIC", "user", role="npd_staff", prefill="npd_pic"),
    ],
)

VALIDATION = define(
    key="validation_mass_production",
    name="Validation Mass Production",
    short_name="Validation",
    description="Validasi produksi massal. Result: PASS / FAIL / PASS WITH CONDITION.",
    kind="decision",
    pic_role="npd_staff",
    actor_roles=["npd_staff", "quality", "production"],
    upload_roles=["npd_staff", "quality", "production"],
    requires_document=True,
    required_doc_types=["validation_report"],
    suggested_doc_types=["validation_report", "trial_photo", "other"],
    requires_approval=True,
    approval_type="validation",
    approver_type="internal",
    outcomes=VALIDATION_OUTCOMES,
    default_next_action="Jalankan validasi mass production & upload report",
    duration_days=5,
    folder="09 Validation",
    record_type="validation",
    calendar_category="validation",
    fields=[
        field("validation_date", "Validation Date", "date", required=True, prefill="today"),
        field("machine", "Machine", required=True),
        field("mold", "Mold"),
        field("cavity", "Cavity", "number"),
        field("material", "Material"),
        field("production_quantity", "Production Quantity (pcs)", "number", required=True),
        field("parameter", "Parameter", "textarea"),
        field("result", "Result", "textarea"),
        field("problem", "Problem", "textarea"),
        field("corrective_action", "Corrective Action", "textarea"),
    ],
)

FINISH = define(
    key="finish",
    name="Finish",
    description="Project menjadi Completed hanya jika seluruh mandatory process selesai.",
    kind="finish",
    pic_role="npd_staff",
    default_next_action="Review kelengkapan & tutup project",
    duration_days=1,
    folder="09 Validation",
    fields=[field("closing_note", "Catatan Penutupan", "textarea")],
)

# =========================================================================== SUBCONT (PRD §4)
SUBCONT_PROCESSES = [
    define(
        key="npr",
        name="NPR",
        description="Admin Sales membuat dan mengirim New Product Request (NPR).",
        pic_role="admin_sales",
        upload_roles=["admin_sales", "npd_staff"],
        requires_document=True,
        required_doc_types=["npr"],
        suggested_doc_types=["npr", "customer_document"],
        default_next_action="Lengkapi data NPR & upload NPR Document",
        duration_days=2,
        folder="01 NPR",
        fields=request_fields("NPR Number"),
    ),
    define(
        key="npd_feedback",
        name="NPD Feedback NPR",
        short_name="NPD Feedback",
        description="NPD Staff memberi feedback, feasibility, risiko, dan rekomendasi.",
        kind="decision",
        pic_role="npd_staff",
        suggested_doc_types=["feedback", "technical_drawing"],
        requires_approval=True,
        approval_type="npr",
        approver_type="internal",
        outcomes=[
            {"key": "accepted", "label": "Accepted", "tone": "positive", "target": {"kind": "next"}, "approval_status": "approved"},
            {"key": "need_revision", "label": "Need Revision", "tone": "neutral", "target": {"kind": "process", "key": "npr"}, "approval_status": "revision_required", "requires_comment": True},
            {"key": "need_info", "label": "Need More Information", "tone": "neutral", "target": {"kind": "process", "key": "npr"}, "approval_status": "revision_required", "requires_comment": True},
            {"key": "rejected", "label": "Rejected", "tone": "negative", "target": {"kind": "cancel"}, "approval_status": "rejected", "requires_comment": True},
        ],
        default_next_action="Berikan feedback & feasibility NPR",
        duration_days=3,
        folder="02 NPD Feedback",
        fields=FEEDBACK_FIELDS,
    ),
    define(
        key="artwork",
        name="Artwork Development",
        short_name="Artwork",
        description="Drafter NPD membuat artwork (AI/PDF/EPS/SVG/PNG/JPG).",
        pic_role="drafter",
        upload_roles=["drafter", "npd_staff"],
        requires_document=True,
        required_doc_types=["artwork"],
        suggested_doc_types=["artwork", "technical_drawing"],
        default_next_action="Selesaikan artwork & upload file",
        duration_days=5,
        folder="03 Artwork",
        fields=[
            field("artwork_name", "Artwork Name", required=True),
            field("product", "Product", prefill="product_name"),
            field("size", "Size", placeholder="mis. 50 x 120 mm"),
            field("material", "Material"),
            field("color", "Color"),
            field("printing_method", "Printing Method", "select", options=["Offset", "Silk Screen", "Hot Stamping", "Heat Transfer", "IML", "Pad Printing", "Digital Print"]),
            field("decoration", "Decoration"),
            field("drafter", "Drafter", "user", role="drafter", prefill="drafter"),
            field("deadline", "Deadline", "date"),
        ],
    ),
    define(
        key="sales_submit_artwork",
        name="Sales Submit Artwork",
        short_name="Submit Artwork",
        description="Sales mengirim artwork ke Customer. Status otomatis: Waiting Customer.",
        pic_role="admin_sales",
        suggested_doc_types=["customer_document", "other"],
        default_next_action="Submit artwork terbaru ke customer",
        duration_days=1,
        folder="04 Customer Approval",
        fields=[
            field("submission_date", "Submission Date", "date", required=True, prefill="today"),
            field("sales_pic", "Sales PIC", "user", required=True, role="admin_sales", prefill="sales_pic"),
            field("customer", "Customer", prefill="customer"),
            field("artwork_revision", "Artwork Revision", "doc_revision", required=True, doc_type="artwork"),
            field("submission_note", "Submission Note", "textarea"),
        ],
    ),
    define(
        key="customer_artwork_approval",
        name="Customer Artwork Approval",
        short_name="Artwork Approval",
        description="Keputusan Customer via Sales. Not Approved -> Artwork Revision -> Sales Resubmit.",
        kind="decision",
        pic_role="admin_sales",
        actor_roles=["admin_sales", "npd_staff"],
        upload_roles=["admin_sales", "npd_staff"],
        suggested_doc_types=["approval", "customer_document"],
        requires_approval=True,
        approval_type="artwork",
        approver_type="customer",
        waiting_type="customer",
        outcomes=customer_decision("artwork"),
        default_next_action="Follow up customer approval",
        duration_days=5,
        folder="04 Customer Approval",
        calendar_category="customer_approval",
    ),
    define(
        key="trial_material_prep",
        name="Trial Material Preparation",
        short_name="Trial Material",
        description="Persiapan material untuk trial: spesifikasi, supplier, batch, masterbatch.",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "purchasing"],
        upload_roles=["npd_staff", "purchasing"],
        requires_document=True,
        required_doc_types=["material_spec", "material_request"],
        suggested_doc_types=["material_spec", "material_request", "supplier_document", "other"],
        default_next_action="Siapkan material trial & jadwalkan trial",
        duration_days=5,
        folder="06 Material",
        fields=[
            field("material", "Material", required=True),
            field("material_type", "Material Type", "select", options=MATERIAL_TYPES),
            field("supplier", "Supplier", prefill="supplier"),
            field("quantity", "Quantity (kg)", "number"),
            field("batch", "Batch"),
            field("color", "Color"),
            field("masterbatch", "Masterbatch"),
            field("trial_requirement", "Trial Requirement", "textarea"),
            field("trial_date", "Trial Date", "date", required=True),
            field("pic", "PIC", "user", role="npd_staff", prefill="npd_pic"),
        ],
    ),
    define(
        key="trial_evaluation",
        name="Trial & Evaluation",
        short_name="Trial",
        description="Trial produksi dan evaluasi hasil (visual, dimension, leak, drop, dll).",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "production", "quality"],
        upload_roles=["npd_staff", "production", "quality"],
        requires_document=True,
        required_doc_types=["trial_report"],
        suggested_doc_types=["trial_report", "trial_photo", "trial_video"],
        default_next_action="Jalankan trial & upload trial report",
        duration_days=4,
        folder="05 Trial / T0",
        record_type="trial",
        calendar_category="trial",
        fields=trial_fields("Trial"),
    ),
    define(
        key="sales_submit_trial",
        name="Sales Submit Trial Result",
        short_name="Submit Trial",
        description="Sales mengirim hasil trial ke Customer.",
        pic_role="admin_sales",
        suggested_doc_types=["trial_report", "trial_photo", "customer_document"],
        default_next_action="Kirim hasil trial ke customer",
        duration_days=1,
        folder="05 Trial / T0",
        fields=[
            field("trial_number", "Trial Number"),
            field("revision", "Revision", placeholder="mis. Rev 00"),
            field("submission_date", "Submission Date", "date", required=True, prefill="today"),
            field("sales_pic", "Sales PIC", "user", required=True, role="admin_sales", prefill="sales_pic"),
            field("customer", "Customer", prefill="customer"),
            field("trial_result", "Trial Result", "select", options=TRIAL_RESULT),
            field("comment", "Comment", "textarea"),
        ],
    ),
    define(
        key="customer_trial_approval",
        name="Customer Trial Approval",
        short_name="Trial Approval",
        description="Keputusan Customer atas hasil trial. Not Approved -> trial revision loop.",
        kind="decision",
        pic_role="admin_sales",
        actor_roles=["admin_sales", "npd_staff"],
        upload_roles=["admin_sales", "npd_staff"],
        suggested_doc_types=["approval", "customer_document"],
        requires_approval=True,
        approval_type="trial",
        approver_type="customer",
        waiting_type="customer",
        outcomes=customer_decision("trial_evaluation", alternatives=["trial_material_prep"]),
        default_next_action="Follow up approval hasil trial ke customer",
        duration_days=5,
        folder="04 Customer Approval",
        calendar_category="customer_approval",
    ),
    define(
        key="bulk_material_request",
        name="Bulk Material Request",
        short_name="Material Request",
        description="Permintaan material bulk ke Purchasing. Ref: FORM-NPD-12, SOP-PUR-03, SOP-PUR-01.",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "purchasing"],
        upload_roles=["npd_staff", "purchasing"],
        requires_document=True,
        required_doc_types=["material_request"],
        suggested_doc_types=["material_request", "material_spec"],
        default_next_action="Ajukan material request ke Purchasing",
        duration_days=3,
        folder="06 Material",
        record_type="material_request",
        fields=[
            field("mr_number", "Material Request Number", required=True, helper="Form: FORM-NPD-12"),
            field("material", "Material", required=True),
            field("supplier", "Supplier", required=True, prefill="supplier"),
            field("quantity", "Quantity (kg)", "number", required=True),
            field("specification", "Specification", "textarea"),
            field("required_date", "Required Date", "date", required=True),
            field("purchasing_pic", "Purchasing PIC", "user", role="purchasing"),
            field("npd_pic", "NPD PIC", "user", role="npd_staff", prefill="npd_pic"),
            field("request_date", "Request Date", "date", prefill="today"),
        ],
    ),
    deepcopy(MATERIAL_PREPARATION),
    deepcopy(VALIDATION),
    deepcopy(FINISH),
]

# =========================================================================== NEW MOLD (PRD §5)
NEW_MOLD_PROCESSES = [
    define(
        key="project_request",
        name="Project Request",
        description="Request project new mold dari Customer melalui Sales.",
        pic_role="admin_sales",
        actor_roles=["admin_sales", "npd_staff"],
        upload_roles=["admin_sales", "npd_staff"],
        requires_document=True,
        required_doc_types=["npr", "customer_document"],
        suggested_doc_types=["npr", "customer_document", "technical_drawing"],
        default_next_action="Lengkapi project request & dokumen customer",
        duration_days=2,
        folder="01 NPR",
        fields=request_fields("Request Number"),
    ),
    define(
        key="npd_feedback",
        name="NPD Feedback",
        description="Feedback & feasibility, termasuk keputusan New Masterbatch (YES/NO).",
        kind="decision",
        pic_role="npd_staff",
        suggested_doc_types=["feedback", "technical_drawing"],
        requires_approval=True,
        approval_type="npr",
        approver_type="internal",
        outcomes=[
            {"key": "accepted_masterbatch", "label": "Accepted · New Masterbatch: YES", "tone": "positive", "target": {"kind": "process", "key": "masterbatch_dev"}, "approval_status": "approved", "sets_new_masterbatch": True},
            {"key": "accepted", "label": "Accepted · New Masterbatch: NO", "tone": "positive", "target": {"kind": "process", "key": "prototype_3d"}, "approval_status": "approved", "sets_new_masterbatch": False},
            {"key": "need_revision", "label": "Need Revision", "tone": "neutral", "target": {"kind": "process", "key": "project_request"}, "approval_status": "revision_required", "requires_comment": True},
            {"key": "rejected", "label": "Rejected", "tone": "negative", "target": {"kind": "cancel"}, "approval_status": "rejected", "requires_comment": True},
        ],
        default_next_action="Berikan feedback & tentukan New Masterbatch",
        duration_days=3,
        folder="02 NPD Feedback",
        fields=FEEDBACK_FIELDS,
    ),
    define(
        key="masterbatch_dev",
        name="Masterbatch Development",
        short_name="Masterbatch",
        description="Pengembangan masterbatch/warna baru bersama supplier.",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "purchasing"],
        upload_roles=["npd_staff", "purchasing"],
        suggested_doc_types=["material_spec", "supplier_document", "trial_photo"],
        default_next_action="Kembangkan masterbatch bersama supplier",
        duration_days=7,
        branch_group="design",
        branch="masterbatch",
        folder="06 Material",
        fields=[
            field("masterbatch_code", "Masterbatch Code", required=True),
            field("color_target", "Color Target", required=True, placeholder="mis. Pantone 7430 C"),
            field("supplier", "Supplier", prefill="supplier"),
            field("let_down_ratio", "Let Down Ratio", placeholder="mis. 2%"),
            field("result", "Result", "textarea"),
        ],
    ),
    define(
        key="masterbatch_approval",
        name="Customer Masterbatch Approval",
        short_name="MB Approval",
        description="Persetujuan Customer atas warna/masterbatch.",
        kind="decision",
        pic_role="admin_sales",
        actor_roles=["admin_sales", "npd_staff"],
        upload_roles=["admin_sales", "npd_staff"],
        suggested_doc_types=["approval", "customer_document"],
        requires_approval=True,
        approval_type="masterbatch",
        approver_type="customer",
        waiting_type="customer",
        outcomes=customer_decision("masterbatch_dev", approve_to="drawing_2d"),
        default_next_action="Follow up approval masterbatch ke customer",
        duration_days=4,
        branch_group="design",
        branch="masterbatch",
        folder="04 Customer Approval",
        calendar_category="customer_approval",
    ),
    define(
        key="prototype_3d",
        name="3D Prototype Development",
        short_name="3D Prototype",
        description="Drafter membuat desain 3D dan prototype.",
        pic_role="drafter",
        upload_roles=["drafter", "npd_staff"],
        requires_document=True,
        required_doc_types=["drawing_3d"],
        suggested_doc_types=["drawing_3d", "trial_photo"],
        default_next_action="Selesaikan 3D & prototype",
        duration_days=6,
        branch_group="design",
        branch="3d",
        folder="07 Mold / Drawing",
        fields=[
            field("design_name", "Design Name", required=True),
            field("prototype_method", "Prototype Method", "select", options=["3D Print SLA", "3D Print FDM", "CNC", "Lainnya"]),
            field("drafter", "Drafter", "user", role="drafter", prefill="drafter"),
            field("notes", "Catatan desain", "textarea"),
        ],
    ),
    define(
        key="approval_3d",
        name="Customer 3D Approval",
        short_name="3D Approval",
        description="Persetujuan Customer atas desain 3D/prototype.",
        kind="decision",
        pic_role="admin_sales",
        actor_roles=["admin_sales", "npd_staff"],
        upload_roles=["admin_sales", "npd_staff"],
        suggested_doc_types=["approval", "customer_document"],
        requires_approval=True,
        approval_type="3d",
        approver_type="customer",
        waiting_type="customer",
        outcomes=customer_decision("prototype_3d"),
        default_next_action="Follow up approval 3D ke customer",
        duration_days=4,
        branch_group="design",
        branch="3d",
        folder="04 Customer Approval",
        calendar_category="customer_approval",
    ),
    define(
        key="drawing_2d",
        name="2D Drawing",
        description="Drafter membuat 2D drawing sebagai dasar mold drawing.",
        pic_role="drafter",
        upload_roles=["drafter", "npd_staff"],
        requires_document=True,
        required_doc_types=["drawing_2d"],
        suggested_doc_types=["drawing_2d", "mold_drawing", "technical_drawing"],
        default_next_action="Selesaikan 2D drawing",
        duration_days=4,
        folder="07 Mold / Drawing",
        fields=[
            field("drawing_number", "Drawing Number", required=True),
            field("critical_dimension", "Critical Dimension / Tolerance", "textarea"),
            field("drafter", "Drafter", "user", role="drafter", prefill="drafter"),
        ],
    ),
    define(
        key="mold_drawing_approval",
        name="Mold Drawing Approval",
        short_name="Mold Drawing",
        description="Persetujuan mold drawing sebelum mold machining.",
        kind="decision",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "admin_sales"],
        upload_roles=["npd_staff", "drafter", "admin_sales"],
        suggested_doc_types=["mold_drawing", "approval"],
        requires_approval=True,
        approval_type="mold_drawing",
        approver_type="customer",
        waiting_type="customer",
        outcomes=customer_decision("drawing_2d"),
        default_next_action="Follow up approval mold drawing",
        duration_days=4,
        folder="07 Mold / Drawing",
        calendar_category="customer_approval",
    ),
    define(
        key="mold_machining",
        name="Mold Machining",
        description="Pembuatan mold oleh Mold Maker.",
        pic_role="npd_staff",
        upload_roles=["npd_staff", "purchasing"],
        suggested_doc_types=["supplier_document", "mold_drawing", "trial_photo"],
        waiting_type="external",
        waiting_label="Mold Maker",
        default_next_action="Monitor progress machining di mold maker",
        duration_days=30,
        folder="07 Mold / Drawing",
        fields=[
            field("mold_maker", "Mold Maker", required=True, prefill="supplier"),
            field("po_number", "PO Number"),
            field("progress", "Progress (%)", "number"),
            field("notes", "Catatan", "textarea"),
        ],
    ),
    define(
        key="t0_trial",
        name="T0 Trial & Evaluation",
        short_name="T0 Trial",
        description="Trial T0 mold baru. T0 Not OK -> Mold Correction -> Mold Machining -> T0.",
        kind="decision",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "production", "quality"],
        upload_roles=["npd_staff", "production", "quality"],
        requires_document=True,
        required_doc_types=["trial_report"],
        suggested_doc_types=["trial_report", "trial_photo", "trial_video"],
        requires_approval=True,
        approval_type="t0",
        approver_type="internal",
        outcomes=[
            {"key": "t0_ok", "label": "T0 OK", "tone": "positive", "target": {"kind": "process", "key": "mold_shipment"}, "approval_status": "approved"},
            {"key": "t0_ng", "label": "T0 Not OK", "tone": "negative", "target": {"kind": "process", "key": "mold_correction"}, "approval_status": "rejected", "requires_comment": True},
        ],
        default_next_action="Jalankan T0 trial & evaluasi hasil",
        duration_days=3,
        folder="05 Trial / T0",
        record_type="trial",
        calendar_category="trial",
        fields=trial_fields("T0"),
    ),
    define(
        key="mold_correction",
        name="Mold Correction",
        description="Perbaikan mold setelah T0 Not OK. Setelah selesai kembali ke Mold Machining.",
        pic_role="npd_staff",
        is_mandatory=False,
        loop_only=True,
        next_key="mold_machining",
        suggested_doc_types=["mold_drawing", "supplier_document"],
        waiting_type="external",
        waiting_label="Mold Maker",
        default_next_action="Koordinasikan perbaikan mold dengan mold maker",
        duration_days=10,
        folder="07 Mold / Drawing",
        fields=[
            field("correction_items", "Correction Items", "textarea", required=True),
            field("mold_maker", "Mold Maker", prefill="supplier"),
            field("estimated_finish", "Estimated Finish", "date"),
        ],
    ),
    define(
        key="mold_shipment",
        name="Mold Shipment",
        description="Pengiriman mold dari mold maker ke pabrik.",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "purchasing"],
        upload_roles=["npd_staff", "purchasing"],
        suggested_doc_types=["supplier_document", "other"],
        waiting_type="external",
        waiting_label="Mold Maker",
        default_next_action="Konfirmasi jadwal pengiriman mold",
        duration_days=5,
        folder="07 Mold / Drawing",
        fields=[
            field("shipment_date", "Shipment Date", "date", required=True, prefill="today"),
            field("delivery_note", "Delivery Note No."),
            field("received_by", "Received By"),
            field("condition", "Condition", "select", required=True, options=["Baik", "Perlu Perbaikan"]),
        ],
    ),
    define(
        key="commissioning_trial",
        name="Commissioning Trial",
        short_name="Commissioning",
        description="Trial commissioning mold di mesin produksi.",
        kind="decision",
        pic_role="npd_staff",
        actor_roles=["npd_staff", "production", "quality"],
        upload_roles=["npd_staff", "production", "quality"],
        requires_document=True,
        required_doc_types=["trial_report"],
        suggested_doc_types=["trial_report", "trial_photo", "trial_video"],
        requires_approval=True,
        approval_type="commissioning",
        approver_type="internal",
        outcomes=[
            {"key": "ok", "label": "Commissioning OK", "tone": "positive", "target": {"kind": "next"}, "approval_status": "approved"},
            {"key": "ng", "label": "Commissioning Not OK", "tone": "negative", "target": {"kind": "repeat"}, "approval_status": "rejected", "requires_comment": True},
        ],
        default_next_action="Jalankan commissioning trial",
        duration_days=4,
        folder="08 Commissioning",
        record_type="trial",
        calendar_category="commissioning",
        fields=trial_fields("Commissioning"),
    ),
    deepcopy(MATERIAL_PREPARATION),
    deepcopy(VALIDATION),
    deepcopy(FINISH),
]


def default_workflows() -> list[dict]:
    return [
        {"id": "wf-subcont", "project_type": "subcont", "name": "Subcont Workflow", "processes": deepcopy(SUBCONT_PROCESSES)},
        {"id": "wf-new-mold", "project_type": "new_mold", "name": "New Mold Workflow", "processes": deepcopy(NEW_MOLD_PROCESSES)},
    ]
